apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-web-application-mysql
  name: todo-web-application-mysql
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: todo-web-application-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-web-application-mysql
    spec:
      containers:
      - image: lalitrnagpal/todo-web-application-mysql:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: todo-web-application-mysql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:   # PODS
    app: todo-web-application-mysql
  name: todo-web-application-mysql
  namespace: default
spec:
  ports:
  - nodePort: 31413
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-application-mysql
  sessionAffinity: ClientIP
  type: LoadBalancer