apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-12-17T05:39:17Z","reason":"ReadyForNewScale","message":"recommended
      size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2020-12-17T05:39:17Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2020-12-17T05:39:17Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":6,"currentAverageValue":"31m"}}]'
  creationTimestamp: "2020-12-17T05:38:56Z"
  name: currency-exchange
  namespace: default
  resourceVersion: "16230"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/currency-exchange
  uid: 251f9612-4dc1-4ac1-a269-c944d0784c21
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currency-exchange
  targetCPUUtilizationPercentage: 10
status:
  currentCPUUtilizationPercentage: 6
  currentReplicas: 1
  desiredReplicas: 1
  lastScaleTime: "2020-12-17T05:55:00Z"