apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-11T04:59:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "38588"
  selfLink: /api/v1/namespaces/default/services/hello-world-rest-api
  uid: bcf58edd-c5de-4a11-b8bc-fcbe625b0f11
spec:
  clusterIP: 10.80.14.159
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31413
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.232.59.110
